In [1]:
import pandas as pd
# import wbdata

In [2]:
df = pd.read_csv('data/.notshared/essential_indicators.csv')
df.head()

,economy,Country,Internet_Usage,GDP_USD,GDP_per_Capita,Poverty_Rate,Total_Population
0,AFG,Afghanistan,17.7089,1.715223e+10,413.757895,NaN,42647492.0
1,ALB,Albania,83.1356,2.704643e+10,11377.775743,0.3,2377128.0
2,DZA,Algeria,76.9081,2.693223e+11,5752.990767,0.0,46814308.0
3,ASM,American Samoa,0.0000,8.710000e+08,18017.458938,NaN,46765.0
4,AND,Andorra,95.4456,4.039842e+09,49303.649167,NaN,81938.0

In [3]:
df = df.fillna("-")
df.head()

,economy,Country,Internet_Usage,GDP_USD,GDP_per_Capita,Poverty_Rate,Total_Population
0,AFG,Afghanistan,17.7089,17152234636.8715,413.757895,-,42647492.0
1,ALB,Albania,83.1356,27046429296.667301,11377.775743,0.3,2377128.0
2,DZA,Algeria,76.9081,269322281664.77301,5752.990767,0.0,46814308.0
3,ASM,American Samoa,0.0,871000000.0,18017.458938,-,46765.0
4,AND,Andorra,95.4456,4039842405.48117,49303.649167,-,81938.0

In [4]:
if type(df.iloc[0]['GDP_USD']) is float:

    # add $ signs
    mask = df['GDP_USD'] != "-"
    df.loc[mask, 'GDP_USD'] = '$' + df['GDP_USD'].loc[mask].astype(str)

    mask = df['GDP_per_Capita'] != "-"
    df.loc[mask, 'GDP_per_Capita'] = '$' + df['GDP_per_Capita'].astype(str)

    mask = df['Poverty_Rate'] != "-"
    df.loc[mask, 'Poverty_Rate'] = (df['Poverty_Rate']*100).astype(str) + '%'

df.head()

,economy,Country,Internet_Usage,GDP_USD,GDP_per_Capita,Poverty_Rate,Total_Population
0,AFG,Afghanistan,17.7089,$17152234636.8715,$413.757894705303,-,42647492.0
1,ALB,Albania,83.1356,$27046429296.6673,$11377.7757431099,30.0%,2377128.0
2,DZA,Algeria,76.9081,$269322281664.773,$5752.99076651465,0.0%,46814308.0
3,ASM,American Samoa,0.0,$871000000.0,$18017.4589383973,-,46765.0
4,AND,Andorra,95.4456,$4039842405.48117,$49303.6491674336,-,81938.0

In [5]:
# # replace periods with commas
# Replaces all '.' with ',' and returns a new DataFrame of strings
df_formatted = df.astype(str).replace(r'\.', ',', regex=True)
df_formatted.to_csv('data/essential_indicators_messy.csv')